# Generated by Django 6.0.6 on 2026-06-15 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0004_doctorprofile_address_doctorprofile_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_doctors', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده (قدیمی)'),
        ),
    ]
