# Generated by Django 6.0.6 on 2026-06-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0005_doctorprofile_approved_at_doctorprofile_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک عکس پروفایل'),
        ),
    ]
